{
 "title": "Number of calls to endpoints",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "query": {
     "query": "label_values(kube_pod_info, namespace)"
    }
   },
   {
    "name": "pod",
    "query": {
     "query": "label_values(kube_pod_status_phase{namespace=~\"$namespace\",phase=\"Running\"},pod)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Number of calls to server",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(main_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} total requests"
    }
   ]
  },
  {
   "title": "Number of calls online_check",
   "type": "stat",
   "gridPos": { "h": 5, "w": 7, "x": 8, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(online_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls online check"
    }
   ]
  },
  {
   "title": "Number of calls to main endpoint",
   "type": "stat",
   "gridPos": { "h": 5, "w": 9, "x": 15, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(main_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls main endpoint"
    }
   ]
  },
  {
   "title": "Number of calls to healthcheck endpoint in the last hour",
   "type": "stat",
   "gridPos": { "h": 11, "w": 24, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(last_over_time(healthcheck_requests_total[$__rate_interval])) by (pod)",
     "legendFormat": "{{pod}} calls healthcheck"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"memory\"}",
     "legendFormat": "limit {{pod}}"
    },
    {
     "expr": "container_memory_usage_bytes{namespace=\"$namespace\"}",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  },
  {
   "title": "CPU Usage",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 24, "x": 0, "y": 33 },
   "targets": [
    {
     "expr": "kube_pod_container_resource_requests{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "requests {{pod}}"
    },
    {
     "expr": "kube_pod_container_resource_limits{namespace=\"$namespace\", resource=\"cpu\"}",
     "legendFormat": "Usage {{pod}}"
    },
    {
     "expr": "rate(container_cpu_usage_seconds_total{namespace=\"pdftron-webviewer\", cluster=\"$cluster\", container!=\"\"}[$__rate_interval])",
     "legendFormat": "Usage {{pod}}"
    }
   ]
  }
 ]
}