name: Build and Push

on:
  release:
    types:
      - published


permissions:
  contents: write
  packages: write

jobs:
  build:
    name: Build & Push
    runs-on: ubuntu-latest
    env:
      DOCKER_CLI_EXPERIMENTAL: "enabled"
    steps:

      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get component version
        run: |
          echo "COMPONENT_VERSION=v$(echo ${{ github.event.release.name }} | awk -F '-v' '{print $NF}')" >> $GITHUB_ENV

      - name: Get component name
        run: |
          echo "COMPONENT_NAME=$(echo ${{ github.event.release.name }} | sed 's/-${{ env.COMPONENT_VERSION }}//')" >> $GITHUB_ENV

      - name: Check component name and component version
        run: |
          echo "COMPONENT_NAME: ${{ env.COMPONENT_NAME }}"
          echo "COMPONENT_VERSION: ${{ env.COMPONENT_VERSION }}"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Docker Login
        uses: docker/login-action@v1
        id: configure-login-ghcr
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ghcr.io/${{ github.repository }}/${{ env.COMPONENT_NAME }}
          tags: |
            type=semver,pattern={{raw}},value=${{ env.COMPONENT_VERSION }}
            type=raw,value=latest

      - name: Build and push
        uses: docker/build-push-action@v5
        with:
          push: true
          platforms: linux/amd64,linux/arm64,linux/arm/v7
          file:  ${{ env.COMPONENT_NAME }}/Dockerfile
          context: ${{ env.COMPONENT_NAME }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args:
            VERSION=${{ env.COMPONENT_VERSION }}
